import json, requests

sources= ['abc-news-au',
          'al-jazeera-english',
          'ars-technica',
          'associated-press',
          'bbc-news',
          'bbc-sport',
          'bild',
          'bloomberg',
          'breitbart-news',
          'business-insider',
          'business-insider-uk',
          'buzzfeed',
          'cnbc',
          'cnn',
          'daily-mail',
          'der-tagesspiegel',
          'die-zeit',
          'engadget',
          'entertainment-weekly',
          'espn',
          'espn-cric-info',
          'financial-times',
          'focus',
          'football-italia',
          'fortune',
          'four-four-two',
          'fox-sports',
          'google-news',
          'gruenderszene',
          'hacker-news',
          'handelsblatt',
          'ign',
          'independent',
          'mashable',
          'metro',
          'mirror',
          'mtv-news',
          'mtv-news-uk',
          'national-geographic',
          'new-scientist',
          'newsweek',
          'new-york-magazine',
          'nfl-news',
          'polygon',
          'recode',
          'reddit-r-all',
          'reuters',
          'spiegel-online',
          't3n',
          'talksport',
          'techcrunch',
          'techradar',
          'the-economist',
          'the-guardian-au',
          'the-guardian-uk',
          'the-hindu',
          'the-huffington-post',
          'the-lad-bible',
          'the-new-york-times',
          'the-next-web',
          'the-sport-bible',
          'the-telegraph',
          'the-times-of-india',
          'the-verge',
          'the-wall-street-journal',
          'the-washington-post',
          'time',
          'usa-today',
          'wired-de',
          'wirtschafts-woche' ]

for api in sources:
    # print('https://newsapi.org/v1/articles?source=' + api + '&sortBy=latest&apiKey=b506a06468994fcc9ed9f55451000921')
    call = requests.get('https://newsapi.org/v1/articles?source=' + api + '&sortBy=latest&apiKey=b506a06468994fcc9ed9f55451000921')
    payload = json.loads(call.text)
    print(payload)